### ISSUE TITLE
Convert "agent" binary into a package

### ISSUE THREAD

**Issue by gustavosbarreto** [shellhub-io/shellhub#2930]
### Description

Currently, we have a binary that is generated from the source code located in the "agent" directory. However, we would like to convert this agent into a package so that it can be used outside the binary as well. This will enable us to create an instance of the agent without the need to execute a binary.

## Task

* [x] Refactor the "agent" code to remove any dependencies on the binary execution.
* [x] Organize the "agent" code into a Go package structure.
* [x] Update the necessary import statements and dependencies to ensure the package can be utilized independently.
* [ ] Test the converted package to ensure it functions correctly when used outside the binary.
* [x] Document the steps required to instantiate and use the agent package separately from the binary.

### Edition

Community

### Version

master

**Comment by brycedjohnson** [comment]
That would be really useful for my integration into a buildroot package: #2913.  

I did very hacky pull out the agent into a separate package here. https://github.com/brycedjohnson/shellhub-agent

It works but mostly just messing around, I hadn't done any work in go before.  Switched back to use earlier version of go since 1.20 wasn't support in buildroot yet (there is a patchset in to do this and it appears to work though).  Also pulled out username/password auth (just use private key), sftp and a few other things.  Was hoping to reduce the agent size down , currently around 7.8MB with `-ldflags "-X main.AgentVersion=latest -s -w" -gcflags=all="-l -B" -trimpath`

Happy to test anything you are working on, I'm sure it will look way way better then when I hacked together!
