### ISSUE TITLE
Migration compatibility issue after updating `mongo-migrate` to `0.4.0`

### ISSUE THREAD

**Issue by gustavosbarreto** [shellhub-io/shellhub#4343]
## Description  
The update of the `mongo-migrate` dependency from version `0.3.2` to `0.4.0` broke the API compilation because of changes in the library. Now, we need to update our code to make it compatible with the new version. 

The problem is that we already have **82 migration files**, and updating all of them to work with the new `mongo-migrate` version could be very hard and take a lot of time. Because of that, we need to analyze another possible solution: **squashing all migrations into one single migration**. This means we will create only one migration with the current state of the database and remove all the old migration files.

## Plan  
1. **Analyze the breaking changes**:  
   - Check what changed in `mongo-migrate` version `0.4.0` and what needs to be updated in our API code.  

2. **Decide on migration handling**:  
   - Analyze the effort needed to update all the existing migrations.  
   - Consider if it’s better to squash all migrations into one single file and remove the old ones.  

3. **Update and test**:  
   - Update the API migration logic for the new version.  
   - If we squash, create the new migration and test it in an environment with data from previous migrations.  

## Tasks  
- [ ] Investigate the breaking changes in `mongo-migrate@0.4.0`.  
- [ ] Check the API migration code and list all necessary changes.  
- [ ] Decide if we will update all migrations or squash them.  
- [ ] Implement the solution and run tests.  

## References  

Dependency update: #4328
