### ISSUE TITLE
0.7.0 release checklist

### ISSUE THREAD

**Issue by gustavosbarreto** [shellhub-io/shellhub#906]
This issue identifies all of the tasks that need to be completed for the minor release. Each task owner is responsible to communicate in this issue about status and check when done and ready.

These tasks need to be completed before we can proceed with the 0.7.0 release:

- [x] Create the changelog. @gustavosbarreto
- [x] Ensure that the documentation for the newly cli backend is updated. @Asakiz 
- [x] Executes a regression test that migrations still happen. @eduardoveiga
- [x] Update shellhub package revision to 'release' branch in `admin-api` and` cloud-api`. @leonardojoao
- [x] Add redis container to helm chart. @otavio @ruan-oliveira
- [x] Do final QA on the release branch (one last check to ensure everything works as expected when merged together). @shellhub-io/core team

These tasks need to be completed after 0.7.0 release:

- [x] Bump shellhub version in the yocto recipe. @Ossanes 
- [x] Bump shellhub version in documentation. @gustavosbarreto 
- [x] Bump shellhub version in nixpkgs. @otavio

**Comment by otavio** [comment]
https://github.com/shellhub-io/meta-shellhub/pull/9
